"""add emoji to categories

Revision ID: bf60588c9a06
Revises: af95eaa7e277
Create Date: 2026-04-02 03:49:58.987306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf60588c9a06'
down_revision: Union[str, None] = 'af95eaa7e277'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('emoji', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'emoji')
    # ### end Alembic commands ###
